### ISSUE TITLE
Support for whisper API

### ISSUE THREAD

**Issue by camberg23** [B4PT0R/streamlit-mic-recorder#1]
Hello, great work on this tool! It works really well, but I would love to use the OpenAI Whisper API with it, can you advise on the best way to do this within this codebase?

**Comment by B4PT0R** [comment]
For the record, here is how the speech_to_text function is implemented using the Recognizer and AudioData from the SpeechRecognition module :
```python
def speech_to_text(start_prompt="Start recording",stop_prompt="Stop recording",just_once=False,use_container_width=False,language='en',key=None):
    audio = mic_recorder(start_prompt=start_prompt,stop_prompt=stop_prompt,just_once=just_once,use_container_width=use_container_width,key=key)
    if audio is None:
        return None
    else:
        r = Recognizer()
        audio_data = AudioData(audio['bytes'],audio['sample_rate'],audio['sample_width'])
        try:
            text = r.recognize_google(audio_data,language=language)
            return text
        except:
            return ""
```
As you can see, it's built on top of the mic_recorder widget. You could do the same to create your own function that uses the Whisper API instead of the SpeechRecognition module to make the transcription. This could look something like this : 
```python
def WhisperSTT(start_prompt="Start recording",stop_prompt="Stop recording",just_once=False,use_container_width=False,key=None):
    audio = mic_recorder(start_prompt=start_prompt,stop_prompt=stop_prompt,just_once=just_once,use_container_width=use_container_width,key=key)
    if audio is None:
        return None
    else:
        audio_BIO = io.BytesIO(audio['bytes'])
        success=False
        err=0
        text=None
        while not success and err<=3:
            try:
                transcript = openai.Audio.transcribe("whisper-1", audio_BIO)
            except Exception as e:
                print(str(e))
                err+=1
            else:
                success=True
                text=transcript['text']
        return text
```

**Comment by nikhilno1** [comment]
Thanks for providing the reference code. I was able to get it to work after adding below lines:
```
if not '_last_audio_id' in state:
    state._last_audio_id=0    
```

`audio_BIO.name = "audio.mp3"`

**Comment by B4PT0R** [comment]
Hello!
Thanks for your feedback.
You made me realize that I should have initialized the '_last_audio_id' state variable directly in the mic_recorder function, so that the user doesn't have to bother about it.
I'll correct this.
By the way, did you try setting the blob name to "audio.wav" rather than "audio.mp3"? Would make more sense, as the bytes are in wav format.

Cheers!

Baptiste

(I'm closing this issue as it seems mostly solved)
